# Generated by Django 2.2.3 on 2021-06-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuenta', '0002_auto_20210601_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_Transaccion', models.CharField(max_length=20)),
                ('monto_Transaccion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_Transaccion', models.DateField(auto_now=True)),
                ('id_Cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuenta.Cuenta')),
            ],
        ),
    ]
