# Generated by Django 2.2.3 on 2021-06-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_Cuenta', models.CharField(max_length=20)),
                ('tipo_Cuenta', models.CharField(max_length=20)),
                ('fecha_Creacion', models.DateField(auto_now=True)),
                ('saldo_Dsiponible', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
            ],
        ),
    ]
