# Generated by Django 2.2.3 on 2021-06-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_Creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
