# Generated by Django 2.2.3 on 2021-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20210601_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_Cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='drop_Cuenta',
            field=models.CharField(choices=[('T. Ahorros', 'Ahorros'), ('T. Ahorros', 'Corriente')], default='T. Ahorros', max_length=2),
        ),
    ]
