# Generated by Django 2.2.3 on 2021-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_auto_20210602_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='drop_Cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='Tipo',
            field=models.CharField(choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], default='Ahorros', max_length=20),
        ),
    ]
